spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}

spring.jpa.hibernate.ddl-auto=none

jwt.secret=${JWTKey}
jwt.access-expiration-ms=${JWT_ACCESS_EXPIRATION_MS}
jwt.refresh-expiration-ms=${JWT_REFRESH_EXPIRATION_MS}

server.port=${AUTH_PORT}
