spring.application.name=profile
server.port=${PROFILE_PORT}

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

minio.url=${MINIO_URL}
minio.bucket=${MINIO_BUCKET}
minio.access-key=${MINIO_ACCESS_KEY}
minio.secret-key=${MINIO_SECRET_KEY}

logging.level.root=INFO
logging.level.com.example.profile=DEBUG