// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB89cCTN3npMfSu1w_fRTba0mm4kuJuqO0',
    appId: '1:152721828895:web:0a91ed62fd83a6232e392a',
    messagingSenderId: '152721828895',
    projectId: 'solver-7984d',
    authDomain: 'solver-7984d.firebaseapp.com',
    storageBucket: 'solver-7984d.firebasestorage.app',
    measurementId: 'G-MFE1Y0T890',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCQNHwpgVOpBKUvrY7K85GWMJlNjq3qqo',
    appId: '1:152721828895:android:e41e29cb499ec39e2e392a',
    messagingSenderId: '152721828895',
    projectId: 'solver-7984d',
    storageBucket: 'solver-7984d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBL9PFZveNLzC5pAMP9RuIlI0KTEpfcJU',
    appId: '1:152721828895:ios:9b23a377b169068f2e392a',
    messagingSenderId: '152721828895',
    projectId: 'solver-7984d',
    storageBucket: 'solver-7984d.firebasestorage.app',
    androidClientId: '152721828895-k26k5qqjeruv6osgaqg5sk82q76dls3o.apps.googleusercontent.com',
    iosClientId: '152721828895-50nlli005h10okgqmohu8fj34qhe118t.apps.googleusercontent.com',
    iosBundleId: 'com.example.streamlit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBL9PFZveNLzC5pAMP9RuIlI0KTEpfcJU',
    appId: '1:152721828895:ios:9b23a377b169068f2e392a',
    messagingSenderId: '152721828895',
    projectId: 'solver-7984d',
    storageBucket: 'solver-7984d.firebasestorage.app',
    androidClientId: '152721828895-k26k5qqjeruv6osgaqg5sk82q76dls3o.apps.googleusercontent.com',
    iosClientId: '152721828895-50nlli005h10okgqmohu8fj34qhe118t.apps.googleusercontent.com',
    iosBundleId: 'com.example.streamlit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB89cCTN3npMfSu1w_fRTba0mm4kuJuqO0',
    appId: '1:152721828895:web:d8d974aa073378c02e392a',
    messagingSenderId: '152721828895',
    projectId: 'solver-7984d',
    authDomain: 'solver-7984d.firebaseapp.com',
    storageBucket: 'solver-7984d.firebasestorage.app',
    measurementId: 'G-6NWTH82MZF',
  );

}